version: "3.9"
services:
  base:
    image: build_image
    build:
      context: .
      dockerfile: Dockerfile
      args:
        POETRY_DEV: ${POETRY_DEV:-true}

  worker1:
    container_name: worker1
    depends_on:
      - base
      - rabbit
    env_file:
      - env-api-dev
    image: build_image

    environment:
      WAIT_HOSTS: rabbit:5672
      WAIT_LOGGER_LEVEL: error
      WAIT_TIMEOUT: 60
      WAIT_SLEEP_INTERVAL: 5
      PYDEVD_DISABLE_FILE_VALIDATION: 1
      RABBITMQ_URL: "amqp://rabbit:5672/test"
      RABBITMQ_USER: admin
      RABBITMQ_PASSWORD: 1234
    volumes:
      - ./src/:/app:cached
    command:
      - /bin/sh
      - -c
      - |
        /wait &&
        watchmedo auto-restart --directory=/app --pattern="*.py;*.yaml" --recursive -- \
        /bin/bash -c 'python app/kombu_worker.py'
  rabbit:
    container_name: rabbit
    image: rabbitmq:3.10.5-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 1234
      RABBITMQ_DEFAULT_VHOST: test
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit log_levels [{connection,error}] -rabbitmq_management"

    ports:
      - 5672:5672 # AMQP protocol port
      - 15672:15672 # HTTP management UI
    volumes:
      - rabbit_data:/var/lib/rabbitmq/mnesia:delegated # Persistent local volume
      - ./rabbit.conf:/etc/rabbitmq/rabbitmq.conf # RabbitMQ configuration file

volumes:
  rabbit_data:
